# Generated by Django 3.1.3 on 2020-11-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estado_tarea_tarea_tipo_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_Tarea',
        ),
    ]
