# Generated by Django 3.1.3 on 2020-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_estado_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
