# Generated by Django 3.1.3 on 2020-11-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_estado_tarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado_tarea',
            options={'verbose_name': 'Estado de Tarea', 'verbose_name_plural': 'Estado de Tareas'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='tipo_usuario',
            options={'verbose_name': 'Tipo de Usuario', 'verbose_name_plural': 'Tipos de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_tip',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_tip_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipo_usuario'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='cierre',
            field=models.DateTimeField(),
        ),
    ]
