# Generated by Django 3.1.3 on 2020-11-19 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201118_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_tip_usu',
            new_name='id_tipo_usuario',
        ),
        migrations.AddField(
            model_name='tarea',
            name='id_estado_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estado_tarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
